version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/tcg_db?sslmode=disable
      - DB_USER=stepanzalis
      - DB_PASS=stepanzalis
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:16-alpine
    container_name: tcg_postgres
    restart: always
    environment:
      - POSTGRES_USER=stepanzalis
      - POSTGRES_PASSWORD=stepanzalis
      - POSTGRES_DB=tcg_db
    # Keep this if you want to connect to DB via DBeaver from your laptop
    # If this fails with "port allocated" too, change 5433 to 5434
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=512MB
      -c effective_cache_size=1GB
      -c work_mem=16MB
      -c maintenance_work_mem=128MB
      -c synchronous_commit=off 
      -c max_connections=100

  redis:
    image: redis:alpine
    container_name: tcg_redis
    restart: always
    # You usually don't need this exposed to the internet, but acceptable for dev
    ports:
      - "6379:6379"

volumes:
  postgres_data: