[versions]
kotlin-version = "2.1.10"
# Ktor modules should all use the same version
ktor-version = "3.3.3"
logback-version = "1.5.21"
exposed-version = "0.61.0" # Or 1.0.0-rc if you are adventurous
h2-version = "2.3.232"
postgresql-version = "42.7.8"
flyway-version = "11.19.0"
hikari-version = "5.1.0"
koin-version = "4.1.1" # Stable release
fuzzywuzzy-version = "1.4.0" # Stable
jackson-version = "2.20.1"
shadow-version = "8.3.6"
tcgdex-version = "2.0.2"
jedis-version = "5.2.0"

[libraries]
# KTOR
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor-version" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor-version" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor-version" }
ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit", version.ref = "ktor-version" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-version" }

# CLIENT
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor-version" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }

# SERIALIZATION
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }

# DI
koin = { module = "io.insert-koin:koin-ktor", version.ref = "koin-version" }
koin-logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin-version" }

# DATABASE
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-version" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed-version" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed-version" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed-version" } # Needed for JSONB!

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql-version" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari-version" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway-version" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway-version" }

# UTILS
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
fuzzywuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzywuzzy-version" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-version" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-version" }
tcgdex = { module = "net.tcgdex:java-sdk", version.ref = "tcgdex-version"}
jedis = { module = "redis.clients:jedis", version.ref = "jedis-version" }

kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-version" }